spring:
  redis:
    uri: redis://localhost:6379
    time-to-live: 60000
  datasource:
    url: jdbc:mysql://localhost:3306/pravin
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update